In [4]:
import tensorflow as tf
import numpy as np

#set_random_seed -> 랜덤으로 발생한 값이 같은 값을 가지게 하기위해서?
tf.set_random_seed(777)

In [39]:
#text data를 가져오기위해 loadtxt -> delimiter = 구분기호
#File이 하나만 있을 경우
xy = np.loadtxt('data.txt' , delimiter=',' ,dtype = np.float32)

In [6]:
'''읽어야할 File이 여러개 일 경우
File Queue -> File Reader -> decode'''

#1. Filename_queue 생성 단계 
#txt파일이 어떤것인지 list에 설정 , shuffle => 무작위로 읽을지?
filename_queue = tf.train.string_input_producer(['data2.csv','data3.csv'] , shuffle=False, name="filename_queue") 

#2. Reader를 생성 단계
#TextLine으로 읽는 reader생성 -> filename_queue에 있는 file list에 속한 txt파일을 읽어서 key와 value에 저장 , value에 읽은 내용이 저장
reader = tf.TextLineReader()
key , value = reader.read(filename_queue)

#3. Decode 단계
# 읽은 data의 형식이 어떤지 지정 0. -> float
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value , record_defaults=record_defaults)

[<tf.Tensor 'DecodeCSV_1:0' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_1:1' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_1:2' shape=() dtype=float32>, <tf.Tensor 'DecodeCSV_1:3' shape=() dtype=float32>]


In [7]:
train_x_batch , train_y_batch = tf.train.batch( [xy[0:-1] ,xy[-1:]] , batch_size = 10)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
#start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord = coord)

for step in range(2001) :
    x_batch , y_batch = sess.run([train_x_batch , train_y_batch])
    cost_val , hy_val , _ = sess.run([cost , hypothesis , train] , feed_dict ={ X : x_batch , Y : y_batch})
    if step % 20 == 0 :
        print(step , " cost : " , cost_val , "\nPrediction : " , hy_val)

coord.request_stop()
coord.join(threads)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
0  cost :  2513.9875 
Prediction :  [[65.16456 ]
 [61.324215]
 [43.673363]
 [35.267197]
 [51.221867]
 [65.16456 ]
 [61.324215]
 [43.673363]
 [35.267197]
 [51.221867]]
20  cost :  1059.0598 
Prediction :  [[117.19564]
 [ 92.72936]
 [ 77.69426]
 [ 42.34132]
 [ 90.15091]
 [117.19564]
 [ 92.72936]
 [ 77.69426]
 [ 42.34132]
 [ 90.15091]]
40  cost :  916.7489 
Prediction :  [[117.72704 ]
 [ 89.0506  ]
 [ 80.11273 ]
 [ 38.319317]
 [ 92.384605]
 [117.72704 ]
 [ 89.0506  ]
 [ 80.11273 ]
 [ 38.319317]
 [ 92.384605]]
60  cost :  803.54297 
Prediction :  [[118.1747  ]
 [ 85.75395 ]
 [ 82.211136]
 [ 34.715057]
 [ 94.315765]
 [118.1747  ]
 [ 85.75395 ]
 [ 82.211136]
 [ 34.715057]
 [ 94.315765]]
80  cost :  713.28906 
Prediction :  [[118.59736 ]
 [ 82.83071 ]
 [ 84.05585 ]
 [ 31.493002]
 [ 96.0137  ]
 [118.59736 ]
 [ 82.83071 ]
 [ 84.05585 ]
 [ 31.493002]
 [ 96.0137  ]]
100  cost :  641.1417 
Prediction :  [[118.99757 

880  cost :  258.1417 
Prediction :  [[127.81497 ]
 [ 60.589172]
 [ 94.37423 ]
 [  0.90524 ]
 [105.57213 ]
 [127.81497 ]
 [ 60.589172]
 [ 94.37423 ]
 [  0.90524 ]
 [105.57213 ]]
900  cost :  256.08112 
Prediction :  [[127.96796   ]
 [ 60.583305  ]
 [ 94.283714  ]
 [  0.74487007]
 [105.49034   ]
 [127.96796   ]
 [ 60.583305  ]
 [ 94.283714  ]
 [  0.74487007]
 [105.49034   ]]
920  cost :  254.07133 
Prediction :  [[128.11894  ]
 [ 60.57973  ]
 [ 94.19277  ]
 [  0.5886996]
 [105.408165 ]
 [128.11894  ]
 [ 60.57973  ]
 [ 94.19277  ]
 [  0.5886996]
 [105.408165 ]]
940  cost :  252.11038 
Prediction :  [[128.268     ]
 [ 60.57818   ]
 [ 94.10158   ]
 [  0.43642795]
 [105.32573   ]
 [128.268     ]
 [ 60.57818   ]
 [ 94.10158   ]
 [  0.43642795]
 [105.32573   ]]
960  cost :  250.19748 
Prediction :  [[128.41513  ]
 [ 60.578392 ]
 [ 94.01031  ]
 [  0.2877676]
 [105.2432   ]
 [128.41513  ]
 [ 60.578392 ]
 [ 94.01031  ]
 [  0.2877676]
 [105.2432   ]]
980  cost :  248.33081 
Prediction :  [[128.56

1740  cost :  202.6708 
Prediction :  [[132.9341  ]
 [ 60.941685]
 [ 90.94991 ]
 [ -3.93563 ]
 [102.4721  ]
 [132.9341  ]
 [ 60.941685]
 [ 90.94991 ]
 [ -3.93563 ]
 [102.4721  ]]
1760  cost :  201.94963 
Prediction :  [[133.02393 ]
 [ 60.951187]
 [ 90.887436]
 [ -4.017376]
 [102.4155  ]
 [133.02393 ]
 [ 60.951187]
 [ 90.887436]
 [ -4.017376]
 [102.4155  ]]
1780  cost :  201.24577 
Prediction :  [[133.11266  ]
 [ 60.96058  ]
 [ 90.8257   ]
 [ -4.0981236]
 [102.35956  ]
 [133.11266  ]
 [ 60.96058  ]
 [ 90.8257   ]
 [ -4.0981236]
 [102.35956  ]]
1800  cost :  200.55899 
Prediction :  [[133.20033  ]
 [ 60.96989  ]
 [ 90.76471  ]
 [ -4.1778708]
 [102.30431  ]
 [133.20033  ]
 [ 60.96989  ]
 [ 90.76471  ]
 [ -4.1778708]
 [102.30431  ]]
1820  cost :  199.88846 
Prediction :  [[133.28696 ]
 [ 60.979088]
 [ 90.70445 ]
 [ -4.256645]
 [102.24972 ]
 [133.28696 ]
 [ 60.979088]
 [ 90.70445 ]
 [ -4.256645]
 [102.24972 ]]
1840  cost :  199.23413 
Prediction :  [[133.3725   ]
 [ 60.988167 ]
 [ 90.64492 

In [1]:
print(xy)

NameError: name 'xy' is not defined

In [42]:
x_data = xy[:,0:-1]
print(x_data)

[[ 70.  80.  90.]
 [ 80.  90. 100.]
 [ 30.  90.  20.]
 [ 60.  70.  80.]]


In [43]:
y_data = xy[:,[-1]]
print(y_data)

[[150.]
 [120.]
 [ 50.]
 [100.]]


In [8]:
X = tf.placeholder(tf.float32 , shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [9]:
W = tf.Variable(tf.random_normal([3,1]) , name="weight")
b = tf.Variable(tf.random_normal([1]) , name="bias")

Instructions for updating:
Colocations handled automatically by placer.


In [10]:
hypothesis = tf.matmul(X,W) + b

In [11]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [12]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [13]:
train = optimizer.minimize(cost)

In [34]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001) :
    cost_val , hy_val , _ = sess.run([cost , hypothesis , train] , feed_dict ={ X : x_data , Y : y_data})
    if step % 20 == 0 :
        print(step , " cost : " , cost_val , "\nPrediction : " , hy_val)

0  cost :  85947.055 
Prediction :  [[-210.68721 ]
 [-235.15028 ]
 [ -25.079748]
 [-186.22418 ]]
20  cost :  2301.8728 
Prediction :  [[105.8733 ]
 [120.38453]
 [134.7677 ]
 [ 91.36207]]
40  cost :  1446.6455 
Prediction :  [[110.0539  ]
 [124.87972 ]
 [114.376305]
 [ 95.22808 ]]
60  cost :  953.79626 
Prediction :  [[113.14258]
 [128.19586]
 [ 98.8456 ]
 [ 98.08928]]
80  cost :  669.77094 
Prediction :  [[115.4873 ]
 [130.7125 ]
 [ 87.05578]
 [100.26211]]
100  cost :  506.08563 
Prediction :  [[117.26732]
 [132.62221]
 [ 78.10581]
 [101.91242]]
120  cost :  411.7496 
Prediction :  [[118.618645]
 [134.0712  ]
 [ 71.311646]
 [103.166084]]
140  cost :  357.37817 
Prediction :  [[119.644516]
 [135.17044 ]
 [ 66.154015]
 [104.11861 ]]
160  cost :  326.03693 
Prediction :  [[120.42337 ]
 [136.00418 ]
 [ 62.238724]
 [104.84256 ]]
180  cost :  307.96774 
Prediction :  [[121.01468]
 [136.63638]
 [ 59.26653]
 [105.39299]]
200  cost :  297.54706 
Prediction :  [[121.4636 ]
 [137.11557]
 [ 57.010

1780  cost :  281.96066 
Prediction :  [[122.897705]
 [138.40213 ]
 [ 49.9037  ]
 [107.39329 ]]
1800  cost :  281.94324 
Prediction :  [[122.89796 ]
 [138.39925 ]
 [ 49.903763]
 [107.39667 ]]
1820  cost :  281.92587 
Prediction :  [[122.8982 ]
 [138.39636]
 [ 49.90381]
 [107.40004]]
1840  cost :  281.9086 
Prediction :  [[122.89845]
 [138.3935 ]
 [ 49.90387]
 [107.40342]]
1860  cost :  281.89136 
Prediction :  [[122.89869 ]
 [138.39061 ]
 [ 49.903915]
 [107.40679 ]]
1880  cost :  281.87393 
Prediction :  [[122.89894 ]
 [138.38773 ]
 [ 49.90398 ]
 [107.410164]]
1900  cost :  281.8566 
Prediction :  [[122.89919 ]
 [138.38486 ]
 [ 49.90403 ]
 [107.413536]]
1920  cost :  281.83917 
Prediction :  [[122.899445]
 [138.38197 ]
 [ 49.904087]
 [107.41691 ]]
1940  cost :  281.822 
Prediction :  [[122.89969]
 [138.3791 ]
 [ 49.90414]
 [107.42027]]
1960  cost :  281.80475 
Prediction :  [[122.899925]
 [138.37622 ]
 [ 49.904194]
 [107.42363 ]]
1980  cost :  281.78754 
Prediction :  [[122.900185]
 [1

In [35]:
print(sess.run(hypothesis , feed_dict={ X : [[30,40,50]]}))

[[61.0208]]


In [37]:
print(sess.run(hypothesis , feed_dict={ X : [[30,40,50] , [70,80,90]]}))

[[ 61.0208 ]
 [122.90044]]
