In [4]:
import tensorflow as tf
import numpy as np

#set_random_seed -> 랜덤으로 발생한 값이 같은 값을 가지게 하기위해서?
tf.set_random_seed(777)

In [7]:
#text data를 가져오기위해 loadtxt -> delimiter = 구분기호
xy = np.loadtxt('data.txt' , dtype = np.float32)

In [21]:
print(xy)

[[ 70.  80.  90. 150.]
 [ 80.  90. 100. 120.]
 [ 30.  90.  20.  50.]
 [ 60.  70.  80. 100.]]


In [18]:
x_data = xy[:,0:-1]
print(x_data)

[[ 70.  80.  90.]
 [ 80.  90. 100.]
 [ 30.  90.  20.]
 [ 60.  70.  80.]]


In [23]:
y_data = xy[:,[-1]]
print(y_data)

[[150.]
 [120.]
 [ 50.]
 [100.]]


In [25]:
X = tf.placeholder(tf.float32 , shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [27]:
W = tf.Variable(tf.random_normal([3,1]) , name="weight")
b = tf.Variable(tf.random_normal([1]) , name="bias")

Instructions for updating:
Colocations handled automatically by placer.


In [28]:
hypothesis = tf.matmul(X,W) + b

In [29]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [30]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [31]:
train = optimizer.minimize(cost)

In [33]:
sess = tf.Session()
sess.run(tf.global_variables_initializer)
for step in range(2001) :
    cost_val , hy_val , _ = sess.run([cost , hypothesis , train] , feed_dict ={ X : x_data , Y : y_data})
    if step % 20 == 0 :
        print(step , " cost : " , cost_val , "\nPrediction : " , hy_val)

TypeError: Fetch argument <function global_variables_initializer at 0x000002187F819B70> has invalid type <class 'function'>, must be a string or Tensor. (Can not convert a function into a Tensor or Operation.)