In [1]:
import tensorflow as tf
import numpy as np

In [2]:
'''Shape , ndim , Slice'''
t = np.array([0.,1.,2.,3.,4.,5.,6.,])

In [9]:
print(t)
print(t.ndim)
print(t.shape)
print(t[0],t[2],t[-1])  #x번째 원소
print(t[2:5] , t[4:-1]) # t[x:y] = x~y-1까지 원소
print(t[:2] , t[3:])    # t[:x] = 맨앞에서 ~ x-1까지

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0 2.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [10]:
a = np.array([[1.,2.,3.] , [4.,5.,6.] ,[7.,8.,9.],[10.,11.,12.] ])

In [11]:
print(a)
print(a.ndim) #rank
print(a.shape) #shape

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2
(4, 3)


In [17]:
sess = tf.Session()
t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

array([4])

In [18]:
a = tf.constant([[1,2] , [3,4]])
tf.shape(a).eval(session=sess)

array([2, 2])

In [20]:
'''Braodcasting'''
matrix1 = tf.constant([3,3])
matrix2 = tf.constant([4,4])
(matrix1 + matrix2).eval(session = sess)


array([7, 7])

In [22]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([4,4])
(matrix1 + matrix2).eval(session = sess)

array([[7, 7]])

In [25]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([4])
(matrix1 + matrix2).eval(session = sess)
# 3+4 , 3+4

array([[7, 7]])

In [26]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[4],[3]])
(matrix1 + matrix2).eval(session = sess)  
# 3+4 , 3+4
# 3+3 , 3+3

array([[7, 7],
       [6, 6]])

In [27]:
'''Reduce Mean'''
tf.reduce_mean([1,2] , axis = 0 ).eval(session=sess)

1

In [35]:
x = [[[1.,2.],[3.,4.]] , [[5.,6.],[7.,8.]]]
tf.reduce_mean(x).eval(session=sess)

4.5

In [39]:
 #축 axis를 기준으로 평균을 구함 
tf.reduce_mean(x , axis = 2).eval(session= sess) 

array([[1.5, 3.5],
       [5.5, 7.5]], dtype=float32)

In [40]:
'''Argmax'''
 #축을 기준으로 가장 큰 원소의 위치
x = [[0,1,2],[2,1,0]]
tf.argmax(x , axis=0).eval(session=sess)  

array([1, 0, 0], dtype=int64)

In [41]:
tf.argmax(x , axis=1).eval(session=sess)

array([2, 0], dtype=int64)

In [42]:
'''Reshape'''
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])

In [43]:
 #맨안쪽의 원소의 수는 거의 고정으로 shape를 조정!
tf.reshape(t, shape=[-1,3]).eval(session = sess)  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
 #하나의 차원으로 묶어줌
tf.squeeze([[0],[1],[2]]).eval(session=sess)

array([0, 1, 2])

In [53]:
#차원을 눌려줌.
tf.expand_dims([[0,1,2]],2).eval(session=sess) 

array([[[0],
        [1],
        [2]]])

In [54]:
x = [[0,1,2]]
tf.shape(x).eval(session=sess)

array([1, 3])

In [55]:
x = [[[0],[1],[2]]]
tf.shape(x).eval(session=sess)

array([1, 3, 1])

In [56]:
'''One hot'''
#depth = 3 이면서 각각의 위치를 설정한 idx만 1로 
tf.one_hot([[0],[1],[2]] , depth=3).eval(session=sess)  

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]]], dtype=float32)

In [58]:
'''Casting'''
#전체 list에 주어진 수를 tf.int32로 casting
tf.cast([1.8,2.2,3.3,4.9] , tf.int32).eval(session=sess) 

array([1, 2, 3, 4])

In [59]:
#list의 true, false를 true -> 1 / false -> 0 으로 casting
tf.cast([True,False, 1==1 , 1==0] , tf.int32).eval(session=sess) 

array([1, 0, 1, 0])

In [60]:
'''Stack'''
x = [1,4]
y = [2,5]
z = [3,6]
# stack에 쌓음
tf.stack([x,y,z]).eval(session=sess)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
# axis축을 부여할 경우 축을 기준으로 stack에 삽입
tf.stack([x,y,z] , axis = 1).eval(session=sess)

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
'''Ones and Zero like'''
x = [[0,1,2],[2,1,0]]

#x와 같은 shape로 ones ~ 1을 넣어서 array를 만듬
tf.ones_like(x).eval(session =sess)

array([[1, 1, 1],
       [1, 1, 1]])

In [63]:
#x와 같은 shape로 zero ~ 0을 넣어서 array를 만듬
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]])

In [67]:
'''zip'''

#list를 묶음
for x,y in zip([1,2,3],[4,5,6]) :
    print(x,y)

1 4
2 5
3 6
